#!/bin/bash

which astyle > /dev/null || { echo "Please install astyle before continuing."; exit 1; }
which vi > /dev/null || { echo "Please install vi before continuing."; exit 1; }

git diff-index --quiet HEAD || { echo "Please commit (or stash) your changes before continuing."; exit 1; }

find . -type f  \
 \( -not -path './navit/support/*' -a -not -path './navit/fib-1.1/*' \) \
 -a \( -iname '*.c' -o -iname '*.cpp' -o -iname '*.java' \) \
-exec \
 astyle --indent=spaces=4 --style=attach -n --max-code-length=120 {} \;

#git commit -am 'cleanup:global:Use astyle to reformat everything'

find . -type f \( -not -path './navit/support/*' -a -not -path './navit/fib-1.1/*' -a -not -path './.git/*' \) \
  -a \( -not -iname '*.bat' \) | while read f; do \
   [[ "$(file -bi $f)" =~ ^text ]] && sed 's/\s*$//' -i $f; done

#git commit -am 'cleanup:cmake:remove trailing spaces'

#find . -iname 'CMakeLists.txt' -exec ex +"set syn=cmake" +"set noexpandtab" +"norm gg=G" -cwq {} \;

#git commit -am 'cleanup:cmake:retab all CMakeLists.txt files'
